name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  BUILD_TYPE: Release
  CC: clang
  CXX: clang++

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21"

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@latest

      - name: Get vcpkg baseline from vcpkg.json
        id: vcpkg-baseline
        run: echo "baseline=$(jq -r '."builtin-baseline"' vcpkg.json)" >> $GITHUB_OUTPUT

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '${{ steps.vcpkg-baseline.outputs.baseline }}'

      - name: Run CMake with Ninja
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'Release_Dist'
          buildPreset: 'Release_Dist'

      - name: Test
        working-directory: ${{github.workspace}}/build/Release
        run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure

      - name: Package Artifact
        working-directory: ${{github.workspace}}/build/Release
        run: ninja package

      - uses: actions/upload-artifact@v4
        with:
          name: lesma-${{ matrix.os }}
          path: ${{github.workspace}}/build/Release/Lesma*.tar.gz

  release:
    name: Release
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Semantic Release Dependencies
        run: |
          npm install -g @semantic-release/changelog @semantic-release/git @google/semantic-release-replace-plugin

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: lesma-*
          merge-multiple: true

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @google/semantic-release-replace-plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}