name: Validate VS Code Extension

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/vscode
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            tools/vscode/package-lock.json
            tools/vscode/client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run compile

      - name: Lint extension
        run: npm run lint
